spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf8
    username: root
    password: root


mybatis-plus:
  type-aliases-package: com.txp.security.model.entity   #多个地址用，隔开
  mapper-locations: classpath:com/txp/security/mapper/xml/*.xml
  global-config:
    db-config:
      logic-not-delete-value: 1
      logic-delete-value: 0